[project]
name = "geometry-calculator-backend"
version = "2.2.0"
description = "几何计算器 后端"
#readme = "README.en.md"
requires-python = ">=3.12"
dependencies = [
    "pywebview>=6.0",
    "sympy>=1.14.0",
]
